export const commonCurrencies = [
  { value: "usd", label: "USD - US Dollar" },
  { value: "eur", label: "EUR - Euro" },
  { value: "try", label: "TRY - Turkish Lira" },
  { value: "syp", label: "SYP - Syrian Pound" },
];
export const currencies = [
  { value: "aed", label: "AED - UAE Dirham" },
  { value: "afn", label: "AFN - Afghan Afghani" },
  { value: "all", label: "ALL - Albanian Lek" },
  { value: "amd", label: "AMD - Armenian Dram" },
  { value: "ang", label: "ANG - Netherlands Antillean Guilder" },
  { value: "aoa", label: "AOA - Angolan Kwanza" },
  { value: "ars", label: "ARS - Argentine Peso" },
  { value: "aud", label: "AUD - Australian Dollar" },
  { value: "awg", label: "AWG - Aruban Florin" },
  { value: "azn", label: "AZN - Azerbaijani Manat" },
  { value: "bam", label: "BAM - Bosnia-Herzegovina Convertible Mark" },
  { value: "bbd", label: "BBD - Barbadian Dollar" },
  { value: "bdt", label: "BDT - Bangladeshi Taka" },
  { value: "bgn", label: "BGN - Bulgarian Lev" },
  { value: "bhd", label: "BHD - Bahraini Dinar" },
  { value: "bif", label: "BIF - Burundian Franc" },
  { value: "bmd", label: "BMD - Bermudan Dollar" },
  { value: "bnd", label: "BND - Brunei Dollar" },
  { value: "bob", label: "BOB - Bolivian Boliviano" },
  { value: "brl", label: "BRL - Brazilian Real" },
  { value: "bsd", label: "BSD - Bahamian Dollar" },
  { value: "btn", label: "BTN - Bhutanese Ngultrum" },
  { value: "bwp", label: "BWP - Botswanan Pula" },
  { value: "byn", label: "BYN - Belarusian Ruble" },
  { value: "bzd", label: "BZD - Belize Dollar" },
  { value: "cad", label: "CAD - Canadian Dollar" },
  { value: "cdf", label: "CDF - Congolese Franc" },
  { value: "chf", label: "CHF - Swiss Franc" },
  { value: "clp", label: "CLP - Chilean Peso" },
  { value: "cny", label: "CNY - Chinese Yuan" },
  { value: "cop", label: "COP - Colombian Peso" },
  { value: "crc", label: "CRC - Costa Rican Colón" },
  { value: "cup", label: "CUP - Cuban Peso" },
  { value: "cve", label: "CVE - Cape Verdean Escudo" },
  { value: "czk", label: "CZK - Czech Koruna" },
  { value: "djf", label: "DJF - Djiboutian Franc" },
  { value: "dkk", label: "DKK - Danish Krone" },
  { value: "dop", label: "DOP - Dominican Peso" },
  { value: "dzd", label: "DZD - Algerian Dinar" },
  { value: "egp", label: "EGP - Egyptian Pound" },
  { value: "ern", label: "ERN - Eritrean Nakfa" },
  { value: "etb", label: "ETB - Ethiopian Birr" },
  { value: "fjd", label: "FJD - Fijian Dollar" },
  { value: "fkp", label: "FKP - Falkland Islands Pound" },
  { value: "gbp", label: "GBP - British Pound" },
  { value: "gel", label: "GEL - Georgian Lari" },
  { value: "ghs", label: "GHS - Ghanaian Cedi" },
  { value: "gip", label: "GIP - Gibraltar Pound" },
  { value: "gmd", label: "GMD - Gambian Dalasi" },
  { value: "gnf", label: "GNF - Guinean Franc" },
  { value: "gtq", label: "GTQ - Guatemalan Quetzal" },
  { value: "gyd", label: "GYD - Guyanaese Dollar" },
  { value: "hkd", label: "HKD - Hong Kong Dollar" },
  { value: "hnl", label: "HNL - Honduran Lempira" },
  { value: "hrk", label: "HRK - Croatian Kuna" },
  { value: "htg", label: "HTG - Haitian Gourde" },
  { value: "huf", label: "HUF - Hungarian Forint" },
  { value: "idr", label: "IDR - Indonesian Rupiah" },
  { value: "ils", label: "ILS - Israeli New Shekel" },
  { value: "inr", label: "INR - Indian Rupee" },
  { value: "iqd", label: "IQD - Iraqi Dinar" },
  { value: "irr", label: "IRR - Iranian Rial" },
  { value: "isk", label: "ISK - Icelandic Króna" },
  { value: "jmd", label: "JMD - Jamaican Dollar" },
  { value: "jod", label: "JOD - Jordanian Dinar" },
  { value: "jpy", label: "JPY - Japanese Yen" },
  { value: "kes", label: "KES - Kenyan Shilling" },
  { value: "kgs", label: "KGS - Kyrgystani Som" },
  { value: "khr", label: "KHR - Cambodian Riel" },
  { value: "kmf", label: "KMF - Comorian Franc" },
  { value: "kpw", label: "KPW - North Korean Won" },
  { value: "krw", label: "KRW - South Korean Won" },
  { value: "kwd", label: "KWD - Kuwaiti Dinar" },
  { value: "kyd", label: "KYD - Cayman Islands Dollar" },
  { value: "kzt", label: "KZT - Kazakhstani Tenge" },
  { value: "lak", label: "LAK - Laotian Kip" },
  { value: "lbp", label: "LBP - Lebanese Pound" },
  { value: "lkr", label: "LKR - Sri Lankan Rupee" },
  { value: "lrd", label: "LRD - Liberian Dollar" },
  { value: "lsl", label: "LSL - Lesotho Loti" },
  { value: "lyd", label: "LYD - Libyan Dinar" },
  { value: "mad", label: "MAD - Moroccan Dirham" },
  { value: "mdl", label: "MDL - Moldovan Leu" },
  { value: "mga", label: "MGA - Malagasy Ariary" },
  { value: "mkd", label: "MKD - Macedonian Denar" },
  { value: "mmk", label: "MMK - Myanmar Kyat" },
  { value: "mnt", label: "MNT - Mongolian Tögrög" },
  { value: "mop", label: "MOP - Macanese Pataca" },
  { value: "mru", label: "MRU - Mauritanian Ouguiya" },
  { value: "mur", label: "MUR - Mauritian Rupee" },
  { value: "mvr", label: "MVR - Maldivian Rufiyaa" },
  { value: "mwk", label: "MWK - Malawian Kwacha" },
  { value: "mxn", label: "MXN - Mexican Peso" },
  { value: "myr", label: "MYR - Malaysian Ringgit" },
  { value: "mzn", label: "MZN - Mozambican Metical" },
  { value: "nad", label: "NAD - Namibian Dollar" },
  { value: "ngn", label: "NGN - Nigerian Naira" },
  { value: "nio", label: "NIO - Nicaraguan Córdoba" },
  { value: "nok", label: "NOK - Norwegian Krone" },
  { value: "npr", label: "NPR - Nepalese Rupee" },
  { value: "nzd", label: "NZD - New Zealand Dollar" },
  { value: "omr", label: "OMR - Omani Rial" },
  { value: "pab", label: "PAB - Panamanian Balboa" },
  { value: "pen", label: "PEN - Peruvian Sol" },
  { value: "pgk", label: "PGK - Papua New Guinean Kina" },
  { value: "php", label: "PHP - Philippine Peso" },
  { value: "pkr", label: "PKR - Pakistani Rupee" },
  { value: "pln", label: "PLN - Polish Złoty" },
  { value: "pyg", label: "PYG - Paraguayan Guaraní" },
  { value: "qar", label: "QAR - Qatari Riyal" },
  { value: "ron", label: "RON - Romanian Leu" },
  { value: "rsd", label: "RSD - Serbian Dinar" },
  { value: "rub", label: "RUB - Russian Ruble" },
  { value: "rwf", label: "RWF - Rwandan Franc" },
  { value: "sar", label: "SAR - Saudi Riyal" },
  { value: "sbd", label: "SBD - Solomon Islands Dollar" },
  { value: "scr", label: "SCR - Seychellois Rupee" },
  { value: "sdg", label: "SDG - Sudanese Pound" },
  { value: "sek", label: "SEK - Swedish Krona" },
  { value: "sgd", label: "SGD - Singapore Dollar" },
  { value: "shp", label: "SHP - St. Helena Pound" },
  { value: "sle", label: "SLE - Sierra Leonean Leone" },
  { value: "sos", label: "SOS - Somali Shilling" },
  { value: "srd", label: "SRD - Surinamese Dollar" },
  { value: "stn", label: "STN - São Tomé & Príncipe Dobra" },
  { value: "svc", label: "SVC - Salvadoran Colón" },
  { value: "szl", label: "SZL - Swazi Lilangeni" },
  { value: "thb", label: "THB - Thai Baht" },
  { value: "tjs", label: "TJS - Tajikistani Somoni" },
  { value: "tmt", label: "TMT - Turkmenistani Manat" },
  { value: "tnd", label: "TND - Tunisian Dinar" },
  { value: "top", label: "TOP - Tongan Paʻanga" },
  { value: "ttd", label: "TTD - Trinidad & Tobago Dollar" },
  { value: "twd", label: "TWD - New Taiwan Dollar" },
  { value: "tzs", label: "TZS - Tanzanian Shilling" },
  { value: "uah", label: "UAH - Ukrainian Hryvnia" },
  { value: "ugx", label: "UGX - Ugandan Shilling" },
  { value: "uyu", label: "UYU - Uruguayan Peso" },
  { value: "uzs", label: "UZS - Uzbekistani Som" },
  { value: "ves", label: "VES - Venezuelan Bolívar" },
  { value: "vnd", label: "VND - Vietnamese Đồng" },
  { value: "vuv", label: "VUV - Vanuatu Vatu" },
  { value: "wst", label: "WST - Samoan Tālā" },
  { value: "xaf", label: "XAF - Central African CFA Franc" },
  { value: "xcd", label: "XCD - East Caribbean Dollar" },
  { value: "xof", label: "XOF - West African CFA Franc" },
  { value: "xpf", label: "XPF - CFP Franc" },
  { value: "yer", label: "YER - Yemeni Rial" },
  { value: "zar", label: "ZAR - South African Rand" },
  { value: "zmw", label: "ZMW - Zambian Kwacha" },
  { value: "zwl", label: "ZWL - Zimbabwean Dollar" },
];
export const allCurrencies = [
  ...commonCurrencies.map((cur) => ({ ...cur, group: "Common" })),
  ...currencies.map((cur) => ({ ...cur, group: "All Currencies" })),
];
